[tool.coverage.run]
branch = true
parallel = true
source = ["."]
relative_files = true

[tool.coverage.html]
show_contexts = true

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "pytest.skip",
]
[tool.mypy]
python_version = "3.10"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = """
  --log-level=NOTSET
  --log-format="%(relativeCreated)4d %(levelname)s %(message)s"
  --tb=short
"""

[tool.ruff]
select = ["ALL"]
ignore = [
  # pydocstyle
  "D",
  # Missing type annotation for `self` in method
  "ANN101",
  # Trailing comma missing
  "COM812",
  # Unnecessary `dict` call (rewrite as a literal)
  "C408",
  # Boolean-typed positional argument in function definition
  "FBT001",
  # Logging statement uses f-string
  "G004",
  # disabled on ruff's recommendation as causes problems with the formatter
  "ISC001",
  # Magic value used in comparison, consider replacing
  "PLR2004",
  # Use of `assert` detected
  "S101",
  # `subprocess` call: check for execution of untrusted input
  "S603",
]

[tool.ruff.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
