name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action
      - run: make lint

  test-matrix:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-matrix.outputs.tests }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action
      - id: set-matrix
        run: make github-test-matrix

  test:
    needs: test-matrix
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        test: ${{ fromJson(needs.test-matrix.outputs.tests) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action
      - run: make test_${{ matrix.test }}-cov
