name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
jobs:
  test-matrix:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-matrix.outputs.tests }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action
      - id: set-matrix
        run: make github-test-matrix
  tests:
    needs: test-matrix
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        test: ${{ fromJson(needs.test-matrix.outputs.tests) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action
      - run: nix develop .#${{ matrix.test }} --command make test-cov ARGV=--pretty
        # to support pretty output
        shell: nix shell "nixpkgs#expect" --command unbuffer bash {0}
        env:
          TERM: linux
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.test }}
          path: coverage
